### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by Mebus** [rbs90/Hanser-book-downloader#1]
Hallo,

can you please tell me, how to compile this?

Mebus

**Comment by rbs90** [comment]
I added an Makefile and some Intellij IDEA project files.
I also created a compiled version: http://down.rbs90.de/Hanser.jar

**Comment by Mebus** [comment]
Great! Thank you! The Makefile worked. And downloading also works!

**Comment by rbs90** [comment]
Nice to hear that someone has the same problem and it works ;-)
